#!/bin/bash
source utils/manage
source .env.user

# config
cp configs/nginx.conf /tmp
if [ ! -z "$WHITELIST" ]; then
    export WHITELIST=$WHITELIST
    whitelist-ip-addresses /tmp/nginx.conf
fi

# install reverse proxy
docker compose --env-file .env.user up -d --remove-orphans --build
docker cp /tmp/nginx.conf nginx-proxy:/etc/nginx

if ! grep -q "#proxy-setup" ~/.bashrc; then
    echo "Modifying .bashrc ..."
    DIR="$( cd "$( dirname -- $0 )" && pwd )"
    echo -e "\n" >> ~/.bashrc
    echo "#proxy-setup" >> ~/.bashrc
    echo "export PROXY_DIR=$DIR" >> ~/.bashrc
    echo 'source $PROXY_DIR/utils/manage' >> ~/.bashrc
    source ~/.bashrc
fi
